version: "3.0"
services:
  elasticsearch:
    build: ./es
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    depends_on:
      - redis

  redis:
    image: redis